### ISSUE TITLE
Prowide for Java 8

### ISSUE THREAD

**Issue by muhammadfarras** [prowide/prowide-iso20022#130]
Thanks for your hard work to provide this beautifull open source project.

Can you provide Prowide ISO20022 for java 8 ? 

Thanks in advance

**Comment by zubri** [comment]
Hi,

Check the release notes, there is a table describing all version branches and the required Java.

https://dev.prowidesoftware.com/SRU2024-9/release-notes/

I strongly recommend you plan a migration to Java 11+ because eventually the Java8 branches will no longer be maintained. 

Starting with SRU2025 version of the standards next year, that go into production by November 2025, we might decommission the Java 8 distributions.
