### ISSUE TITLE
working publishMavenJavaPublicationToMavenLocal

### ISSUE THREAD

**Issue by delanym** [prowide/prowide-iso20022#62]
On the front page https://github.com/prowide/prowide-iso20022

> If instead of depending on the uber jar you want to have a subset of the library for some message types you can just take the base and common jars and the specific category modules.

But how do I get these in a way that I can use them dynamically?

The task `./gradlew publishMavenJavaPublicationToMavenLocal` doesn't work.

**Comment by ptorres-prowide** [comment]
Hello, you can add the following line to the gradle command in order to avoid the error:  `-xpublishMavenJavaPublicationToSonatypeRepositor`

Besides that, please check the last section of the project readme, it explains how to create specific libs for each module.

_If instead of depending on the uber jar you want to have a subset of the library for some message types you can just take the base and common jars and the specific category modules. For instance to use ony the pacs and camt messages, you need:

iso20022-core -> pw-iso20022-core-SRUYYYY-version.jar
model-common-types -> pw-iso20022-common-types-SRUYYYY-version.jar
model-pacs-mx -> pw-iso20022-pacs-mx-SRUYYYY-version.jar
model-pacs-types -> pw-iso20022-pacs-types-SRUYYYY-version.jar
model-camt-mx -> pw-iso20022-camt-mx-SRUYYYY-version.jar
model-camt-types -> pw-iso20022-camt-types-SRUYYYY-version.jar

In this case, you can run the following commands:

./gradlew :iso20022-core:jar
./gradlew :model-common-types:jar
./gradlew :model-pacs-mx:jar
./gradlew :model-pacs-types:jar
./gradlew :model-camt-mx:jar
./gradlew :model-camt-types:jar_
